nvr:
  host: 192.168.2.253
  port: 80
  rtsp_port: 554
  username: admin
  password: changeme

onvif_port: 8080

channels:
  - channel: 1
    ip: 192.168.2.161
    name: "Camera 1"
  - channel: 2
    ip: 192.168.2.162
    name: "Camera 2"
  - channel: 3
    ip: 192.168.2.163
    name: "Camera 3"
  - channel: 4
    ip: 192.168.2.164
    name: "Camera 4"
  - channel: 5
    ip: 192.168.2.165
    name: "Camera 5"
  - channel: 6
    ip: 192.168.2.166
    name: "Camera 6"
  - channel: 7
    ip: 192.168.2.167
    name: "Camera 7"
  - channel: 8
    ip: 192.168.2.168
    name: "Camera 8"
